{% set version = "1.8.1" %}

package:
  name: jsoncpp
  version: {{ version }}

source:
  fn: jsoncpp-{{ version }}.tar.gz
  url: https://github.com/open-source-parsers/jsoncpp/archive/{{ version }}.tar.gz
  sha256: 858db2faf348f89fdf1062bd3e79256772e897e7f17df73e0624edf004f2f9ac

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - pkg-config  # [unix]
    - python
    - msinttypes  # [win and vc==9]

test:
  commands:
    # Verify headers are present.
    - test -f "${PREFIX}/include/json/json.h"      # [unix]
    - if not exist %LIBRARY_INC%\\json\\json.h exit 1  # [win]

    # Verify pkg-config file is present.
    - test -f "${PREFIX}/lib/pkgconfig/jsoncpp.pc"  # [unix]

    # Verify libraries are present.
    - test -f "${PREFIX}/lib/libjsoncpp.a"          # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libjsoncpp${SHLIB_EXT}']"  # [unix]
    - if not exist %LIBRARY_LIB%\\jsoncpp.lib exit 1  # [win]

about:
  home: https://github.com/open-source-parsers/jsoncpp
  license: Public Domain/MIT
  license_file: LICENSE
  summary: A C++ library for interacting with JSON.

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
